#:kivy 2.3.1

WindowManager:

    InicioScreen:
    LoginAdminScreen:
    LoginScreen:
    MenuScreen:
    RegistroScreen:
    MenuAdminScreen:


# ---------------- INICIO ----------------
<InicioScreen>:

    name: "inicio"

    BoxLayout:
        orientation: "vertical"
        padding: 40
        spacing: 20
        canvas.before:
            Color:
                rgba: 0.0, 0.39, 0.25, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "CONTROL DE ASISTENCIA UJAT"
            font_size: "30sp"
            color: 1,1,1,1

        Button:
            text: "Ingresar como Administrador"
            background_color: 0.78, 0.64, 0.29, 1
            color: 0,0,0,1
            on_press:
                app.root.current = "login_admin"

        Button:
            text: "Ingresar como Profesor"
            background_color: 1,1,1,1
            color: 0.0, 0.25, 0.16, 1
            on_press:
                app.root.current = "login"
# ---------------- LOGIN ADMIN ----------------
<LoginAdminScreen>:

    name: "login_admin"

    BoxLayout:
        orientation: "vertical"
        padding: 40

        canvas.before:
            Color:
                rgba: 0.0, 0.39, 0.25, 1
            Rectangle:
                pos: self.pos
                size: self.size

        TextInput:
            id: admin_input
            hint_text: "ID Admin"
            background_color: 1,1,1,1

        Button:
            text: "Entrar"
            background_color: 0.78, 0.64, 0.29, 1
            on_press:
                root.validar_admin()


# ---------------- LOGIN PROFESOR ----------------
<LoginScreen>:

    name: "login"

    BoxLayout:
        orientation: "vertical"
        padding: 40
        spacing: 20

        canvas.before:
            Color:
                rgba: 0.95,0.95,0.95,1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "INGRESA TU ID"
            font_size: "26sp"
            color: 0.0, 0.39, 0.25, 1

        TextInput:
            id: id_input
            multiline: False
            background_color: 1,1,1,1

        Button:
            text: "INGRESAR"
            background_color: 0.0, 0.39, 0.25, 1
            color: 1,1,1,1
            on_press:
                root.validar_usuario()

# ---------------- MENU PROFESOR ----------------
<MenuScreen>:

    name: "menu"

    BoxLayout:
        orientation: "vertical"
        padding: 40
        spacing: 20
        canvas.before:
            Color:
                rgba: 1,1,1,1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "MENÚ UJAT"
            font_size: "36sp"
            color: 0.0, 0.39, 0.25, 1

        Button:
            text: "Registrar Horario"
            background_color: 0.0, 0.39, 0.25, 1
            color: 1,1,1,1
            on_press:
                app.root.current = "registro"

        Button:
            text: "Cerrar Sesión"
            background_color: 0.78, 0.64, 0.29, 1
            color: 0,0,0,1
            on_press:
                app.root.current = "login"


# ---------------- REGISTRO ----------------
<RegistroScreen>:
    name: "registro"

    FloatLayout:

        canvas.before:
            Rectangle:
                source: "logo_ujat.png"
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: "vertical"
            padding: 40
            spacing: 20
            size_hint: 0.85, 0.85
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 0.92
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [15]

            Label:
                text: "REGISTRO DE ASISTENCIA"
                font_size: "28sp"
                bold: True
                color: 0.0, 0.25, 0.16, 1
                size_hint_y: None
                height: 60

            Spinner:
                id: dia_spinner
                text: "Selecciona un día"
                values: ["Lunes","Martes","Miércoles","Jueves","Viernes"]
                size_hint_y: None
                height: 50

            Button:
                text: "REGISTRAR ENTRADA"
                size_hint_y: None
                height: 55
                background_color: 0.0, 0.25, 0.16, 1
                color: 1,1,1,1
                on_press:
                    root.registrar_entrada()

            Button:
                text: "REGISTRAR SALIDA"
                size_hint_y: None
                height: 55
                background_color: 0.78, 0.64, 0.29, 1
                color: 0,0,0,1
                on_press:
                    root.registrar_salida()

            Label:
                text: root.registro
                color: 0,0,0,1
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1] + 20

            Button:
                text: "VOLVER AL MENÚ"
                size_hint_y: None
                height: 55
                background_color: 0.2, 0.2, 0.2, 1
                color: 1,1,1,1
                on_press:
                    app.root.current = "menu"


# ---------------- MENU ADMIN ----------------
<MenuAdminScreen>:

    name: "menu_admin"

    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "PANEL ADMIN"
            font_size: "22sp"

        TextInput:
            id: new_id
            hint_text: "ID profesor"

        TextInput:
            id: new_name
            hint_text: "Nombre profesor"

        Button:
            text: "Agregar profesor"
            on_press: root.agregar_profesor()

        Button:
            text: "Ver profesores"
            on_press: root.cargar_profesores()

        Label:
            id: output_profesores
            text: ""

        Button:
            text: "Ver registros"
            on_press: root.cargar_registros()

        ScrollView:
            Label:
                id: output
                text: ""
                size_hint_y: None
                height: self.texture_size[1]
                text_size: self.width, None

        Button:
            text: "Cerrar sesión"
            on_press: app.root.current = "inicio"